version: '2'


services:
  eap:
    container_name: eap
    build: ./app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - elasticsearch
    volumes:
      - ./app:/usr/src/app
      - ./app:/usr/src/app/static
    env_file: .env
    environment:
      DEBUG: 'true'
    command: /usr/local/bin/python manage.py runserver 0.0.0.0:8080

  postgres:
    restart: always
    container_name: postgres
    image: postgres:9.5.2
    environment:
      POSTGRES_USER: "eap"
      POSTGRES_PASSWORD: "eap"
      POSTGRES_DB: "eap"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    container_name: redis
    image: redis:3.0.7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  elasticsearch:
    restart: always
    container_name: elasticsearch
    image: elasticsearch:2.3.2
    ports:
      - "9200:9200"
      - "9300:9300"

  adminer:
    container_name: adminer
    image: clue/adminer
    ports:
      - "9000:80"

  kibana:
    container_name: kibana
    image: kibana:latest
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"


volumes:
  redisdata:
    driver: local
  pgdata:
    driver: local
