eap:
  container_name: eap
  build: ./app
  command: /usr/local/bin/python manage.py runserver 0.0.0.0:8080
  env_file: .env
  ports:
    - "8080:8080"
  links:
    - postgres:postgres
    - redis:redis
    - elasticsearch:elasticsearch
    - memcached:memcached

postgres:
  restart: always
  container_name: postgres
  image: postgres:9.5.2
  env_file: .env
  ports:
    - "5432:5432"

adminer:
  restart: always
  image: clue/adminer
  links:
    - postgres
  ports:
    - "9000:80"

memcached:
  restart: always
  container_name: memcached
  image: memcached:1.4.25
  ports:
    - "11211:11211"

redis:
  restart: always
  container_name: redis
  image: redis:3.0.7
  ports:
    - "6379:6379"

elasticsearch:
  restart: always
  container_name: elasticsearch
  image: elasticsearch:2.3.2
  ports:
    - "9200:9200"
    - "9300:9300"
