app:
  # restart: always
  build: ./app
  ports:
    - "8080:8080"
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - ./app:/usr/src/app
    - ./app:/usr/src/app/static
  env_file: .env
  environment:
    DEBUG: 'true'
  # command: /usr/local/bin/python manage.py runserver 0.0.0.0:8080
  # command: /usr/local/bin/gunicorn eap.wsgi:application -w 2 -b :8000

nginx:
  # restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - app
  links:
    - app:app

postgres:
  # restart: always
  image: postgres:9.5.2
  environment:
    POSTGRES_USER: "eap"
    POSTGRES_PASSWORD: "eap"
    POSTGRES_DB: "eap"
  ports:
    - "5432:5432"
  volumes:
    - pgdata:/var/lib/postgresql/data/

redis:
  # restart: always
  image: redis:latest
  ports:
    - "6379:6379"
  volumes:
    - redisdata:/data

adminer:
  image: clue/adminer
  links:
    - postgres:postgres
  ports:
    - "9000:80"
