# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20160615_1650'),
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='sync.Crawler')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
