# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('sync', '0002_crawlercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlercategory',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.Brand'),
        ),
        migrations.AddField(
            model_name='crawlercategory',
            name='classifier',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='crawlercategory',
            name='description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlercategory',
            name='name',
            field=models.BooleanField(default=False),
        ),
    ]
