# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='stores')),
                ('meta_keywords', models.TextField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
            ],
        ),
    ]
