# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20160605_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='related_colors',
            new_name='related_items',
        ),
    ]
