# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='test', max_length=64),
            preserve_default=False,
        ),
    ]
