# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='alt',
            field=models.CharField(default='test_alt', max_length=255),
            preserve_default=False,
        ),
    ]
