# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_articleimage_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
    ]
