# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20160521_2014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletter',
            new_name='Subscriber',
        ),
    ]
